apiVersion: apps/v1
kind: Deployment
metadata:
  name: w8t-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w8t-mysql
  template:
    metadata:
      labels:
        app: w8t-mysql
    spec:
      containers:
        - name: w8t-mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: w8t.123
            - name: MYSQL_DATABASE
              value: watchalert
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          hostPath:
            path: /data/w8t/mysql
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: w8t-mysql
  namespace: default
spec:
  selector:
    app: w8t-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306